### ISSUE TITLE
mpv has no slave mode

### ISSUE THREAD

**Issue by andreasvc** [andreasvc/cplay#13]
mpv has replaced mplayer in Debian, but it doesn't support the -slave option.

**Comment by xi** [comment]
I simply added mpv as yet another player: https://github.com/xi/cplay-ng/commit/a0fa576065639573bbfc65925a288bddcdf1bccc

Note that slave mode is not really used by any current version of cplay that I know of. It was originally added in https://github.com/Argafal/cplay/commit/3abf8c06edca3435528d51c9411e47ee91a99013. Argfal added a lot of custom mplayer functionality like euqalizer and speed control that I later removed again.

mplayer also supports seeking via `-ss` (`--start` in mpv). I ended up removing `mplayer_send()` completely in https://github.com/xi/cplay-ng/commit/14a907fb8429beb71a089e1f88f459152d710967
