### ISSUE TITLE
cplay only briefly appears on the help screen

### ISSUE THREAD

**Issue by spiralofhope** [andreasvc/cplay#15]
I see the cplay version briefly appear at the bottom of the help screen, however it disappears quickly.  Perhaps it should be displayed at the top, or kept at the bottom permanently.

Perhaps consider also implementing a `./cplay --version`

I'm using cplay from github current, and Python 2.7.9

**Comment by andreasvc** [comment]
Well, at the moment the version isn't meaningful anyway since I haven't made any releases of this fork. This would mean deciding whether to rename the project etc.
