### ISSUE TITLE
Can no longer play

### ISSUE THREAD

**Issue by spiralofhope** [andreasvc/cplay#18]
commit 97f5693, made for #13, seems to have broken my use of cplay.

- navigate to my mp3s
- `cplay .`
- It begins parsing, but I get `error adding <filename>` for files which have non-English filenames.  (I see one Russian song with a filename in Cyrillic).
- A playlist is populated with entries
- Press `enter` on a filename
- There is a small delay, and then it skips to the next, another delay, skips, etc.

**Comment by spiralofhope** [comment]
The non-English filename errors appear to be fixed, however the playlist problem remains:

- Press enter on a filename
- There is a small delay, and then it skips to the next, another delay, skips, etc.

I fiddled, and it looks like this change did it to me:

``` python
# This works:
    MPlayer('mplayer -slave -vc null -vo null %s',
            r'^https?://|\.(mp[123cp+]|ogg|flac|spx|cdr|wav|aiff|ape|m4a|wma'
            r'|mod|xm|fm|s3m|med|col|669|it|mtm|stm|au)$'),
# This does not:
    MPlayer('mplayer --ss %d %s',
            r'^https?://|\.(mp[123cp+]|ogg|flac|spx|cdr|wav|aiff|ape|m4a|wma'
            r'|mod|xm|fm|s3m|med|col|669|it|mtm|stm|au)$'),
```

At the commandline, `mplayer -ss 0 0 filename.mp3` does work. I'm not sure 

I'm using `MPlayer2 2.0-728-g2c378c7-4+b`, and I re-tried after renaming `~/.mplayer` out of the way.

**Comment by andreasvc** [comment]
Thx for the bug reports!
