### ISSUE TITLE
Removing some features/key bindings

### ISSUE THREAD

**Issue by xi** [andreasvc/cplay#20]
I am considering removing some features from my fork of cplay, namely:

- tags (add/delete/move actions would only be performed on the current item)
- bookmarks
- macros
- shell commands
- stop playlist after each track

Before going ahead with these changes, I wanted to ask of your opinion. Do you have any recommendations? Would you be interested in merging these changes into your code?

**Comment by andreasvc** [comment]
I think the first is useful (BTW tags is confusing terminology because of ID3 tags, selection is better). But apart from the first, I don't use these features either, so removing them might be a good idea.

BTW: what's the status on getting a new cplay package into Debian?

**Comment by xi** [comment]
Good to know that you agree with most of the list.

Can you explain what you do with tags? Maybe I just don't understand them correctly.

> BTW: what's the status on getting a new cplay package into Debian?

Haven't heard of it since. There is probably nobody who wants to do it. Now as you mention it, I could try to package it myself. (Mo promises though)

**Comment by andreasvc** [comment]
Say you add a few albums, but then decide you want them in a different order or remove one of them. You go to playlist, use space to select a bunch of files, then remove them with d or or move them with m. It's the same concept as selecting multiple files in any file manager.
