### ISSUE TITLE
improved cooperation with cplay-ng

### ISSUE THREAD

**Issue by xi** [andreasvc/cplay#6]
I am maintaining a fork of a cplay at https://github.com/xi/cplay-ng. I try to track what you do and port your changes to my fork and I noticed that you also ported some of my changes to your fork. We also did similar refactoring and both worked on python3 compatibility.

Unfortuantly, our forks have diverged nevertheless. It is not simple to cherry-pick a commit from one repo to the other. So I would like to smooth out some of the discrepancies in order to ease collaboration .

I did not yet have a detailed look at the code but there are some obvious problems:

-  We use different coding styles and linters. You use pylint in a [Makefile](https://github.com/andreasvc/cplay/blob/master/Makefile). I use pyflakes with config in [setup.cfg](https://github.com/xi/cplay-ng/blob/master/setup.cfg).

-  We use different formats for the README file. You use markdown. I use reStructureText because that is used on PyPI.

-  I wrapped cplay in a python package, so I had to move `cplay` to `cplay/cplay.py` . That is probably the diversion that causes the most trouble.

When these discrepancies have been resolved we could go on and look at the python code itself. For now I would like to get you feedback on (1) if you think we should do something to improve code portability between our projects and (2) what you think about the three issues described above. I would happily adjust my code or create pull request to yours.

**Comment by andreasvc** [comment]
Collaboration would be cool. Would be nice to become the new Debian upstream of cplay someday.
It seems that pylint is more advanced than pyflakes, so I think pylint is preferable; Makefile vs setup.cfg is not important to me. I don't mind about the README format, so we can switch to rst. A package is also fine, although I think for a single script it is not really necessary. Above all, I'd like to keep cplay simple and avoid feature creep; if you agree on that, joining forces sounds like a good plan.

**Comment by xi** [comment]
Thanks for your feedback!

> It seems that pylint is more advanced than pyflakes, so I think pylint is preferable

I have to correct myself, I actually use [flake8](https://pypi.python.org/pypi/flake8/2.4.0) which combines pyflakes and pep8.

I have no problem with using pylint. But it seems to be very strict. When I ran `make lint` in your repo it showed quite some warnings. Do you have additional config somewhere or do you simply ignore the warnings?

> Above all, I'd like to keep cplay simple and avoid feature creep

I agree completely.

**Comment by xi** [comment]
> I don't mind about the README format, so we can switch to rst. A package is also fine, although I think for a single script it is not really necessary.

I am working on this at https://github.com/xi/cplay-ng/tree/avc-rst. For some reason I cannot create a pul request. I contacted the folks at github about that.

**Comment by xi** [comment]
In my impression the situation has improved quite a bit in the last week. Thanks for your feedback!
